"""Drift and integrity detection for closed-domain RAG logs.

This script reads audit-trail JSONL data and reports drift in:
- retrieval scores
- refusal rate
- groundedness
- query length
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

from app.config import AUDIT_LOG_PATH

PROJECT_ROOT = Path(__file__).resolve().parents[2]
VIS_DIR = PROJECT_ROOT / "visualizations"


def load_audit_log(path: Path) -> pd.DataFrame:
    """Load JSONL audit log generated by the RAG pipeline."""
    if not path.exists():
        raise FileNotFoundError(f"Audit log not found: {path}")
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    if not rows:
        raise ValueError("Audit log is empty.")
    df = pd.DataFrame(rows)
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df["query_length"] = df["query"].fillna("").str.split().str.len()
    return df


def psi(expected: np.ndarray, actual: np.ndarray, bins: int = 10) -> float:
    """Population Stability Index for numeric distribution drift."""
    breakpoints = np.percentile(expected, np.linspace(0, 100, bins + 1))
    breakpoints = np.unique(breakpoints)
    if len(breakpoints) < 3:
        return 0.0
    expected_counts, _ = np.histogram(expected, bins=breakpoints)
    actual_counts, _ = np.histogram(actual, bins=breakpoints)
    expected_pct = np.maximum(expected_counts / max(expected_counts.sum(), 1), 1e-6)
    actual_pct = np.maximum(actual_counts / max(actual_counts.sum(), 1), 1e-6)
    return float(np.sum((actual_pct - expected_pct) * np.log(actual_pct / expected_pct)))


def split_reference_current(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Use first half as reference and second half as current production window."""
    df = df.sort_values("timestamp").reset_index(drop=True)
    mid = max(1, len(df) // 2)
    return df.iloc[:mid], df.iloc[mid:]


def plot_metric(df: pd.DataFrame, metric: str, output: Path, title: str, ylabel: str) -> None:
    """Plot a rolling metric trend."""
    VIS_DIR.mkdir(parents=True, exist_ok=True)
    series = df[metric].astype(float).rolling(window=5, min_periods=1).mean()
    plt.figure(figsize=(10, 5))
    plt.plot(range(len(series)), series)
    plt.title(title)
    plt.xlabel("Request sequence")
    plt.ylabel(ylabel)
    plt.tight_layout()
    plt.savefig(output, dpi=160)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, default=AUDIT_LOG_PATH)
    args = parser.parse_args()

    df = load_audit_log(args.log)
    reference, current = split_reference_current(df)

    retrieval_psi = psi(
        reference["top_retrieval_score"].fillna(0).to_numpy(),
        current["top_retrieval_score"].fillna(0).to_numpy(),
    )
    query_len_psi = psi(
        reference["query_length"].fillna(0).to_numpy(),
        current["query_length"].fillna(0).to_numpy(),
    )
    ks_stat, ks_p = stats.ks_2samp(
        reference["top_retrieval_score"].fillna(0),
        current["top_retrieval_score"].fillna(0),
    )

    refusal_ref = reference["refused"].mean()
    refusal_cur = current["refused"].mean() if len(current) else 0.0
    grounded_ref = reference["grounded"].mean()
    grounded_cur = current["grounded"].mean() if len(current) else 0.0

    plot_metric(df, "top_retrieval_score", VIS_DIR / "retrieval-score-drift.png", "Retrieval Score Drift", "Top retrieval score")
    df["refusal_numeric"] = df["refused"].astype(int)
    plot_metric(df, "refusal_numeric", VIS_DIR / "refusal-rate-drift.png", "Refusal Rate Drift", "Rolling refusal rate")

    print("=== Drift Detection Report ===")
    print(f"Rows analyzed: {len(df)}")
    print(f"Retrieval score PSI: {retrieval_psi:.3f}")
    print(f"Query length PSI: {query_len_psi:.3f}")
    print(f"Retrieval KS statistic={ks_stat:.3f}, p={ks_p:.5f}")
    print(f"Refusal rate reference={refusal_ref:.3f}, current={refusal_cur:.3f}")
    print(f"Groundedness rate reference={grounded_ref:.3f}, current={grounded_cur:.3f}")

    if retrieval_psi > 0.25 or ks_p < 0.05:
        print("Action: investigate retrieval drift, chunking quality, and query mix.")
    elif refusal_cur - refusal_ref > 0.20:
        print("Action: investigate off-topic usage or missing source coverage.")
    else:
        print("Action: no major drift detected; continue monitoring.")


if __name__ == "__main__":
    main()
